# Enable debug info in console
debug-mode: true

# Enable colors in console output
color-logs: true

# Enable misc logging alerts in console output
logging:
  info: true
  warn: true
  error: true

# Language file (for translations)
language-file: lang-en.yml

# Portal Configurations
# Main Portal
portal:
  main:
    # Main portal title
    portal-title: "Main Reach Portal"
    # Item to close the inventory
    close-inventory:
      slot: 0
      type: "APPLE"
      title: "&4Close Inventory"
      lore:
        - "&7Click to close Main"
        - "&7Reach Portal."
    # Item to open up the Tools Portal
    tools-portal:
      slot: 2
      type: "DIAMOND_AXE"
      title: "&7Open Tools Portal"
      lore:
        - "Open Custom Tools Portal"
  tools:
    tree-spawner:
      enabled: true
      slot: 2
      cooldown: 40
      particle:
        spawned-timer: 10
        design: "sphere"
      type: "WOODEN_AXE"
      title: "&4Tree Spawner"
      lore:
        - "&7Spawn a custom tree."
      spawned:
        identifier: 001
        type: "WOODEN_AXE"
        title: "&2Tree Spawner"
        lore:
          - "&7Click location where you would"
          - "&7like to spawn your &6Tree Type&7."
        tool-portal:
          acacia:
            enabled: true
            slot-row: 0
            slot-column: 0
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "ACACIA_LOG"
            title: "Acacia"
            lore:
              - "&7Click here to spawn"
              - "&7the Acacia tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          birch:
            enabled: true
            slot-row: 0
            slot-column: 1
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "BIRCH_LEAVES"
            title: "Birch"
            lore:
              - "&7Click here to spawn"
              - "&7the Birch tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          tall-birch:
            enabled: true
            slot-row: 0
            slot-column: 2
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "BIRCH_LOG"
            title: "Tall Birch"
            lore:
              - "&7Click here to spawn"
              - "&7the Tall Birch tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          spruce:
            enabled: true
            slot-row: 0
            slot-column: 3
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "SPRUCE_LOG"
            title: "Spruce"
            lore:
              - "&7Click here to spawn"
              - "&7the Spruce tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          jungle-bush:
            enabled: true
            slot-row: 0
            slot-column: 4
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "JUNGLE_LEAVES"
            title: "Jungle Bush"
            lore:
              - "&7Click here to spawn"
              - "&7the Jungle Bush tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          small-jungle:
            enabled: true
            slot-row: 0
            slot-column: 5
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "STRIPPED_JUNGLE_LOG"
            title: "Small Jungle"
            lore:
              - "&7Click here to spawn"
              - "&7the Small Jungle tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          jungle:
            enabled: true
            slot-row: 0
            slot-column: 6
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "JUNGLE_LOG"
            title: "Jungle"
            lore:
              - "&7Click here to spawn"
              - "&7the Jungle tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          oak:
            enabled: true
            slot-row: 0
            slot-column: 7
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "OAK_LOG"
            title: "Oak"
            lore:
              - "&7Click here to spawn"
              - "&7the Oak tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          big-oak:
            enabled: true
            slot-row: 0
            slot-column: 8
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "STRIPPED_OAK_LOG"
            title: "Big Oak"
            lore:
              - "&7Click here to spawn"
              - "&7the Big Oak tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          dark-oak:
            enabled: true
            slot-row: 1
            slot-column: 0
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "DARK_OAK_LOG"
            title: "Dark Oak"
            lore:
              - "&7Click here to spawn"
              - "&7the Dark Oak tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          cocoa:
            enabled: true
            slot-row: 1
            slot-column: 1
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "COCOA_BEANS"
            title: "Cocoa"
            lore:
              - "&7Click here to spawn"
              - "&7the Cocoa tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          swamp:
            enabled: true
            slot-row: 1
            slot-column: 2
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "VINE"
            title: "Swamp"
            lore:
              - "&7Click here to spawn"
              - "&7the Swamp tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."
          chorus-plant:
            enabled: true
            slot-row: 1
            slot-column: 3
            cooldown: 60
            particle-spawned-timer: 1
            particle-type: "EXPLOSION_HUGE"
            particle-design: "explode"
            type: "CHORUS_PLANT"
            title: "Chorus Plant"
            lore:
              - "&7Click here to spawn"
              - "&7the Chorus Plant tree type."
              - ""
              - "&7After the tree has"
              - "&7spawned, the tool will "
              - "&7be removed from your inventory."