# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Enable misc logging alerts in console output
info-logging: true
warn-logging: true
error-logging: true

# Language file (for translations)
language-file: lang-en.yml