# Enable debug info in console
debug-mode: true

# Enable colors in console output
color-logs: true

# Enable misc logging alerts in console output
logging:
  info: true
  warn: true
  error: true

# Language file (for translations)
language-file: lang-en.yml

# Portal Configurations
# Main Portal
portal:
  main:
    # Main portal title
    portal-title: "Main Reach Portal"
    # Item to close the inventory
    close-inventory:
      slot: 0
      type: "APPLE"
      title: "&4Close Inventory"
      lore:
        - "&7Click to close Main"
        - "&7Reach Portal."
    # Item to open up the Tools Portal
    tools-portal:
      slot: 2
      type: "DIAMOND_AXE"
      title: "&7Open Tools Portal"
      lore:
        - "Open Custom Tools Portal"
  tools:
    tree-spawner:
      enabled: true
      slot: 2
      cooldown: 40
      particle-spawned-timer: 10
      type: "WOODEN_AXE"
      title: "&4Tree Spawner"
      lore:
        - "&7Spawn a custom tree."