# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Enable misc logging alerts in console output
info-logging: true
warn-logging: true
error-logging: true

# Language file (for translations)
language-file: lang-en.yml

# Portal Configurations
# Main Portal
portal:
  main:
    # Main portal title
    portal-title: "Main Reach Portal"
    # Item to close the inventory
    close-inventory-slot: 0
    close-inventory-type: "APPLE"
    close-inventory-title: "&4Close Inventory"
    close-inventory-lore: "&7Click to close Main\n&7Reach Portal."
    # Item to open up the Tools Portal
    tools-portal-slot: 2
    tools-portal-type: "DIAMOND_AXE"
    tools-portal-title: "&7Open Tools Portal"
    tools-portal-lore: "Open Custom Tools Portal"
  tools:
    tree-spawner-slot: 2
    tree-spawner-type: "WOODEN_AXE"
    tree-spawner-title: "Tree Spawner"
    tree-spawner-lore: "&7Spawn a custom tree."